/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as BuildsIndexRouteImport } from './routes/builds/index'
import { Route as BuildsBuildIdRouteImport } from './routes/builds/$buildId'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsApiTokensRouteImport } from './routes/settings/api-tokens'
import { Route as SettingsArtifactsRouteImport } from './routes/settings/artifacts'
import { Route as SettingsAuditLogRouteImport } from './routes/settings/audit-log'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsRetentionRouteImport } from './routes/settings/retention'
import { Route as SettingsRunnersRouteImport } from './routes/settings/runners'
import { Route as SettingsThemeRouteImport } from './routes/settings/theme'
import { Route as SettingsUsersRouteImport } from './routes/settings/users'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as SetupCompleteRouteImport } from './routes/setup/complete'
import { Route as SetupModeRouteImport } from './routes/setup/mode'
import { Route as SetupOidcRouteImport } from './routes/setup/oidc'
import { Route as SetupOwnerRouteImport } from './routes/setup/owner'
import { Route as SetupTrustedProxyRouteImport } from './routes/setup/trusted-proxy'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as SettingsIntegrationsIndexRouteImport } from './routes/settings/integrations/index'
import { Route as SettingsIntegrationsIntegrationIdRouteImport } from './routes/settings/integrations/$integrationId'
import { Route as SettingsIntegrationsGithubRouteImport } from './routes/settings/integrations/github'
import { Route as SettingsIntegrationsGitlabRouteImport } from './routes/settings/integrations/gitlab'
import { Route as SettingsIntegrationsLocalGitRouteImport } from './routes/settings/integrations/local-git'
import { Route as SettingsNotificationsIndexRouteImport } from './routes/settings/notifications/index'
import { Route as SettingsNotificationsChannelIdRouteImport } from './routes/settings/notifications/$channelId'
import { Route as SettingsNotificationsNewRouteImport } from './routes/settings/notifications/new'
import { Route as ProjectsProjectIdPipelinesPipelineIdRouteImport } from './routes/projects/$projectId/pipelines/$pipelineId'
import { Route as ProjectsProjectIdPipelinesNewRouteImport } from './routes/projects/$projectId/pipelines/new'
import { Route as ProjectsProjectIdPipelinesPipelineIdEditRouteImport } from './routes/projects/$projectId/pipelines/$pipelineId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsBuildIdRoute = BuildsBuildIdRouteImport.update({
  id: '/builds/$buildId',
  path: '/builds/$buildId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsApiTokensRoute = SettingsApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/api-tokens.lazy').then((d) => d.Route),
)
const SettingsArtifactsRoute = SettingsArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAuditLogRoute = SettingsAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/preferences.lazy').then((d) => d.Route),
)
const SettingsRetentionRoute = SettingsRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/retention.lazy').then((d) => d.Route),
)
const SettingsRunnersRoute = SettingsRunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/runners.lazy').then((d) => d.Route),
)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRouteRoute,
} as any).lazy(() =>
  import('./routes/settings/theme.lazy').then((d) => d.Route),
)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any).lazy(() => import('./routes/setup/index.lazy').then((d) => d.Route))
const SetupCompleteRoute = SetupCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => SetupRoute,
} as any)
const SetupModeRoute = SetupModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => SetupRoute,
} as any).lazy(() => import('./routes/setup/mode.lazy').then((d) => d.Route))
const SetupOidcRoute = SetupOidcRouteImport.update({
  id: '/oidc',
  path: '/oidc',
  getParentRoute: () => SetupRoute,
} as any).lazy(() => import('./routes/setup/oidc.lazy').then((d) => d.Route))
const SetupOwnerRoute = SetupOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => SetupRoute,
} as any).lazy(() => import('./routes/setup/owner.lazy').then((d) => d.Route))
const SetupTrustedProxyRoute = SetupTrustedProxyRouteImport.update({
  id: '/trusted-proxy',
  path: '/trusted-proxy',
  getParentRoute: () => SetupRoute,
} as any).lazy(() =>
  import('./routes/setup/trusted-proxy.lazy').then((d) => d.Route),
)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsIndexRoute =
  SettingsIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsIntegrationsIntegrationIdRoute =
  SettingsIntegrationsIntegrationIdRouteImport.update({
    id: '/integrations/$integrationId',
    path: '/integrations/$integrationId',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsIntegrationsGithubRoute =
  SettingsIntegrationsGithubRouteImport.update({
    id: '/integrations/github',
    path: '/integrations/github',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsIntegrationsGitlabRoute =
  SettingsIntegrationsGitlabRouteImport.update({
    id: '/integrations/gitlab',
    path: '/integrations/gitlab',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsIntegrationsLocalGitRoute =
  SettingsIntegrationsLocalGitRouteImport.update({
    id: '/integrations/local-git',
    path: '/integrations/local-git',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsNotificationsIndexRoute =
  SettingsNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsNotificationsChannelIdRoute =
  SettingsNotificationsChannelIdRouteImport.update({
    id: '/notifications/$channelId',
    path: '/notifications/$channelId',
    getParentRoute: () => SettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/settings/notifications/$channelId.lazy').then(
      (d) => d.Route,
    ),
  )
const SettingsNotificationsNewRoute =
  SettingsNotificationsNewRouteImport.update({
    id: '/notifications/new',
    path: '/notifications/new',
    getParentRoute: () => SettingsRouteRoute,
  } as any).lazy(() =>
    import('./routes/settings/notifications/new.lazy').then((d) => d.Route),
  )
const ProjectsProjectIdPipelinesPipelineIdRoute =
  ProjectsProjectIdPipelinesPipelineIdRouteImport.update({
    id: '/projects/$projectId/pipelines/$pipelineId',
    path: '/projects/$projectId/pipelines/$pipelineId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdPipelinesNewRoute =
  ProjectsProjectIdPipelinesNewRouteImport.update({
    id: '/projects/$projectId/pipelines/new',
    path: '/projects/$projectId/pipelines/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdPipelinesPipelineIdEditRoute =
  ProjectsProjectIdPipelinesPipelineIdEditRouteImport.update({
    id: '/projects/$projectId/pipelines/$pipelineId_/edit',
    path: '/projects/$projectId/pipelines/$pipelineId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/builds/$buildId': typeof BuildsBuildIdRoute
  '/settings/api-tokens': typeof SettingsApiTokensRoute
  '/settings/artifacts': typeof SettingsArtifactsRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/retention': typeof SettingsRetentionRoute
  '/settings/runners': typeof SettingsRunnersRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/users': typeof SettingsUsersRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/mode': typeof SetupModeRoute
  '/setup/oidc': typeof SetupOidcRoute
  '/setup/owner': typeof SetupOwnerRoute
  '/setup/trusted-proxy': typeof SetupTrustedProxyRoute
  '/builds/': typeof BuildsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/settings/integrations/$integrationId': typeof SettingsIntegrationsIntegrationIdRoute
  '/settings/integrations/github': typeof SettingsIntegrationsGithubRoute
  '/settings/integrations/gitlab': typeof SettingsIntegrationsGitlabRoute
  '/settings/integrations/local-git': typeof SettingsIntegrationsLocalGitRoute
  '/settings/notifications/$channelId': typeof SettingsNotificationsChannelIdRoute
  '/settings/notifications/new': typeof SettingsNotificationsNewRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexRoute
  '/projects/$projectId/pipelines/$pipelineId': typeof ProjectsProjectIdPipelinesPipelineIdRoute
  '/projects/$projectId/pipelines/new': typeof ProjectsProjectIdPipelinesNewRoute
  '/projects/$projectId/pipelines/$pipelineId/edit': typeof ProjectsProjectIdPipelinesPipelineIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/builds/$buildId': typeof BuildsBuildIdRoute
  '/settings/api-tokens': typeof SettingsApiTokensRoute
  '/settings/artifacts': typeof SettingsArtifactsRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/retention': typeof SettingsRetentionRoute
  '/settings/runners': typeof SettingsRunnersRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/users': typeof SettingsUsersRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/mode': typeof SetupModeRoute
  '/setup/oidc': typeof SetupOidcRoute
  '/setup/owner': typeof SetupOwnerRoute
  '/setup/trusted-proxy': typeof SetupTrustedProxyRoute
  '/builds': typeof BuildsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/setup': typeof SetupIndexRoute
  '/settings/integrations/$integrationId': typeof SettingsIntegrationsIntegrationIdRoute
  '/settings/integrations/github': typeof SettingsIntegrationsGithubRoute
  '/settings/integrations/gitlab': typeof SettingsIntegrationsGitlabRoute
  '/settings/integrations/local-git': typeof SettingsIntegrationsLocalGitRoute
  '/settings/notifications/$channelId': typeof SettingsNotificationsChannelIdRoute
  '/settings/notifications/new': typeof SettingsNotificationsNewRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/settings/integrations': typeof SettingsIntegrationsIndexRoute
  '/settings/notifications': typeof SettingsNotificationsIndexRoute
  '/projects/$projectId/pipelines/$pipelineId': typeof ProjectsProjectIdPipelinesPipelineIdRoute
  '/projects/$projectId/pipelines/new': typeof ProjectsProjectIdPipelinesNewRoute
  '/projects/$projectId/pipelines/$pipelineId/edit': typeof ProjectsProjectIdPipelinesPipelineIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/builds/$buildId': typeof BuildsBuildIdRoute
  '/settings/api-tokens': typeof SettingsApiTokensRoute
  '/settings/artifacts': typeof SettingsArtifactsRoute
  '/settings/audit-log': typeof SettingsAuditLogRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/retention': typeof SettingsRetentionRoute
  '/settings/runners': typeof SettingsRunnersRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/users': typeof SettingsUsersRoute
  '/setup/complete': typeof SetupCompleteRoute
  '/setup/mode': typeof SetupModeRoute
  '/setup/oidc': typeof SetupOidcRoute
  '/setup/owner': typeof SetupOwnerRoute
  '/setup/trusted-proxy': typeof SetupTrustedProxyRoute
  '/builds/': typeof BuildsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/settings/integrations/$integrationId': typeof SettingsIntegrationsIntegrationIdRoute
  '/settings/integrations/github': typeof SettingsIntegrationsGithubRoute
  '/settings/integrations/gitlab': typeof SettingsIntegrationsGitlabRoute
  '/settings/integrations/local-git': typeof SettingsIntegrationsLocalGitRoute
  '/settings/notifications/$channelId': typeof SettingsNotificationsChannelIdRoute
  '/settings/notifications/new': typeof SettingsNotificationsNewRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexRoute
  '/settings/notifications/': typeof SettingsNotificationsIndexRoute
  '/projects/$projectId/pipelines/$pipelineId': typeof ProjectsProjectIdPipelinesPipelineIdRoute
  '/projects/$projectId/pipelines/new': typeof ProjectsProjectIdPipelinesNewRoute
  '/projects/$projectId/pipelines/$pipelineId_/edit': typeof ProjectsProjectIdPipelinesPipelineIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/setup'
    | '/auth/callback'
    | '/builds/$buildId'
    | '/settings/api-tokens'
    | '/settings/artifacts'
    | '/settings/audit-log'
    | '/settings/preferences'
    | '/settings/retention'
    | '/settings/runners'
    | '/settings/theme'
    | '/settings/users'
    | '/setup/complete'
    | '/setup/mode'
    | '/setup/oidc'
    | '/setup/owner'
    | '/setup/trusted-proxy'
    | '/builds/'
    | '/projects/'
    | '/settings/'
    | '/setup/'
    | '/settings/integrations/$integrationId'
    | '/settings/integrations/github'
    | '/settings/integrations/gitlab'
    | '/settings/integrations/local-git'
    | '/settings/notifications/$channelId'
    | '/settings/notifications/new'
    | '/projects/$projectId/'
    | '/settings/integrations/'
    | '/settings/notifications/'
    | '/projects/$projectId/pipelines/$pipelineId'
    | '/projects/$projectId/pipelines/new'
    | '/projects/$projectId/pipelines/$pipelineId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/builds/$buildId'
    | '/settings/api-tokens'
    | '/settings/artifacts'
    | '/settings/audit-log'
    | '/settings/preferences'
    | '/settings/retention'
    | '/settings/runners'
    | '/settings/theme'
    | '/settings/users'
    | '/setup/complete'
    | '/setup/mode'
    | '/setup/oidc'
    | '/setup/owner'
    | '/setup/trusted-proxy'
    | '/builds'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/settings/integrations/$integrationId'
    | '/settings/integrations/github'
    | '/settings/integrations/gitlab'
    | '/settings/integrations/local-git'
    | '/settings/notifications/$channelId'
    | '/settings/notifications/new'
    | '/projects/$projectId'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/projects/$projectId/pipelines/$pipelineId'
    | '/projects/$projectId/pipelines/new'
    | '/projects/$projectId/pipelines/$pipelineId/edit'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/login'
    | '/setup'
    | '/auth/callback'
    | '/builds/$buildId'
    | '/settings/api-tokens'
    | '/settings/artifacts'
    | '/settings/audit-log'
    | '/settings/preferences'
    | '/settings/retention'
    | '/settings/runners'
    | '/settings/theme'
    | '/settings/users'
    | '/setup/complete'
    | '/setup/mode'
    | '/setup/oidc'
    | '/setup/owner'
    | '/setup/trusted-proxy'
    | '/builds/'
    | '/projects/'
    | '/settings/'
    | '/setup/'
    | '/settings/integrations/$integrationId'
    | '/settings/integrations/github'
    | '/settings/integrations/gitlab'
    | '/settings/integrations/local-git'
    | '/settings/notifications/$channelId'
    | '/settings/notifications/new'
    | '/projects/$projectId/'
    | '/settings/integrations/'
    | '/settings/notifications/'
    | '/projects/$projectId/pipelines/$pipelineId'
    | '/projects/$projectId/pipelines/new'
    | '/projects/$projectId/pipelines/$pipelineId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  BuildsBuildIdRoute: typeof BuildsBuildIdRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdPipelinesPipelineIdRoute: typeof ProjectsProjectIdPipelinesPipelineIdRoute
  ProjectsProjectIdPipelinesNewRoute: typeof ProjectsProjectIdPipelinesNewRoute
  ProjectsProjectIdPipelinesPipelineIdEditRoute: typeof ProjectsProjectIdPipelinesPipelineIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/': {
      id: '/builds/'
      path: '/builds'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds/$buildId': {
      id: '/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/builds/$buildId'
      preLoaderRoute: typeof BuildsBuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/api-tokens': {
      id: '/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/settings/api-tokens'
      preLoaderRoute: typeof SettingsApiTokensRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/artifacts': {
      id: '/settings/artifacts'
      path: '/artifacts'
      fullPath: '/settings/artifacts'
      preLoaderRoute: typeof SettingsArtifactsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/audit-log': {
      id: '/settings/audit-log'
      path: '/audit-log'
      fullPath: '/settings/audit-log'
      preLoaderRoute: typeof SettingsAuditLogRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/retention': {
      id: '/settings/retention'
      path: '/retention'
      fullPath: '/settings/retention'
      preLoaderRoute: typeof SettingsRetentionRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/runners': {
      id: '/settings/runners'
      path: '/runners'
      fullPath: '/settings/runners'
      preLoaderRoute: typeof SettingsRunnersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/complete': {
      id: '/setup/complete'
      path: '/complete'
      fullPath: '/setup/complete'
      preLoaderRoute: typeof SetupCompleteRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/mode': {
      id: '/setup/mode'
      path: '/mode'
      fullPath: '/setup/mode'
      preLoaderRoute: typeof SetupModeRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/oidc': {
      id: '/setup/oidc'
      path: '/oidc'
      fullPath: '/setup/oidc'
      preLoaderRoute: typeof SetupOidcRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/owner': {
      id: '/setup/owner'
      path: '/owner'
      fullPath: '/setup/owner'
      preLoaderRoute: typeof SetupOwnerRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/trusted-proxy': {
      id: '/setup/trusted-proxy'
      path: '/trusted-proxy'
      fullPath: '/setup/trusted-proxy'
      preLoaderRoute: typeof SetupTrustedProxyRouteImport
      parentRoute: typeof SetupRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations/': {
      id: '/settings/integrations/'
      path: '/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof SettingsIntegrationsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations/$integrationId': {
      id: '/settings/integrations/$integrationId'
      path: '/integrations/$integrationId'
      fullPath: '/settings/integrations/$integrationId'
      preLoaderRoute: typeof SettingsIntegrationsIntegrationIdRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations/github': {
      id: '/settings/integrations/github'
      path: '/integrations/github'
      fullPath: '/settings/integrations/github'
      preLoaderRoute: typeof SettingsIntegrationsGithubRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations/gitlab': {
      id: '/settings/integrations/gitlab'
      path: '/integrations/gitlab'
      fullPath: '/settings/integrations/gitlab'
      preLoaderRoute: typeof SettingsIntegrationsGitlabRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/integrations/local-git': {
      id: '/settings/integrations/local-git'
      path: '/integrations/local-git'
      fullPath: '/settings/integrations/local-git'
      preLoaderRoute: typeof SettingsIntegrationsLocalGitRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications/': {
      id: '/settings/notifications/'
      path: '/notifications'
      fullPath: '/settings/notifications/'
      preLoaderRoute: typeof SettingsNotificationsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications/$channelId': {
      id: '/settings/notifications/$channelId'
      path: '/notifications/$channelId'
      fullPath: '/settings/notifications/$channelId'
      preLoaderRoute: typeof SettingsNotificationsChannelIdRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/notifications/new': {
      id: '/settings/notifications/new'
      path: '/notifications/new'
      fullPath: '/settings/notifications/new'
      preLoaderRoute: typeof SettingsNotificationsNewRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/projects/$projectId/pipelines/$pipelineId': {
      id: '/projects/$projectId/pipelines/$pipelineId'
      path: '/projects/$projectId/pipelines/$pipelineId'
      fullPath: '/projects/$projectId/pipelines/$pipelineId'
      preLoaderRoute: typeof ProjectsProjectIdPipelinesPipelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/pipelines/new': {
      id: '/projects/$projectId/pipelines/new'
      path: '/projects/$projectId/pipelines/new'
      fullPath: '/projects/$projectId/pipelines/new'
      preLoaderRoute: typeof ProjectsProjectIdPipelinesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/pipelines/$pipelineId_/edit': {
      id: '/projects/$projectId/pipelines/$pipelineId_/edit'
      path: '/projects/$projectId/pipelines/$pipelineId/edit'
      fullPath: '/projects/$projectId/pipelines/$pipelineId/edit'
      preLoaderRoute: typeof ProjectsProjectIdPipelinesPipelineIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsApiTokensRoute: typeof SettingsApiTokensRoute
  SettingsArtifactsRoute: typeof SettingsArtifactsRoute
  SettingsAuditLogRoute: typeof SettingsAuditLogRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsRetentionRoute: typeof SettingsRetentionRoute
  SettingsRunnersRoute: typeof SettingsRunnersRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsIntegrationsIntegrationIdRoute: typeof SettingsIntegrationsIntegrationIdRoute
  SettingsIntegrationsGithubRoute: typeof SettingsIntegrationsGithubRoute
  SettingsIntegrationsGitlabRoute: typeof SettingsIntegrationsGitlabRoute
  SettingsIntegrationsLocalGitRoute: typeof SettingsIntegrationsLocalGitRoute
  SettingsNotificationsChannelIdRoute: typeof SettingsNotificationsChannelIdRoute
  SettingsNotificationsNewRoute: typeof SettingsNotificationsNewRoute
  SettingsIntegrationsIndexRoute: typeof SettingsIntegrationsIndexRoute
  SettingsNotificationsIndexRoute: typeof SettingsNotificationsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsApiTokensRoute: SettingsApiTokensRoute,
  SettingsArtifactsRoute: SettingsArtifactsRoute,
  SettingsAuditLogRoute: SettingsAuditLogRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsRetentionRoute: SettingsRetentionRoute,
  SettingsRunnersRoute: SettingsRunnersRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsIntegrationsIntegrationIdRoute:
    SettingsIntegrationsIntegrationIdRoute,
  SettingsIntegrationsGithubRoute: SettingsIntegrationsGithubRoute,
  SettingsIntegrationsGitlabRoute: SettingsIntegrationsGitlabRoute,
  SettingsIntegrationsLocalGitRoute: SettingsIntegrationsLocalGitRoute,
  SettingsNotificationsChannelIdRoute: SettingsNotificationsChannelIdRoute,
  SettingsNotificationsNewRoute: SettingsNotificationsNewRoute,
  SettingsIntegrationsIndexRoute: SettingsIntegrationsIndexRoute,
  SettingsNotificationsIndexRoute: SettingsNotificationsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface SetupRouteChildren {
  SetupCompleteRoute: typeof SetupCompleteRoute
  SetupModeRoute: typeof SetupModeRoute
  SetupOidcRoute: typeof SetupOidcRoute
  SetupOwnerRoute: typeof SetupOwnerRoute
  SetupTrustedProxyRoute: typeof SetupTrustedProxyRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupCompleteRoute: SetupCompleteRoute,
  SetupModeRoute: SetupModeRoute,
  SetupOidcRoute: SetupOidcRoute,
  SetupOwnerRoute: SetupOwnerRoute,
  SetupTrustedProxyRoute: SetupTrustedProxyRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  BuildsBuildIdRoute: BuildsBuildIdRoute,
  BuildsIndexRoute: BuildsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdPipelinesPipelineIdRoute:
    ProjectsProjectIdPipelinesPipelineIdRoute,
  ProjectsProjectIdPipelinesNewRoute: ProjectsProjectIdPipelinesNewRoute,
  ProjectsProjectIdPipelinesPipelineIdEditRoute:
    ProjectsProjectIdPipelinesPipelineIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
