import { useAuthStore } from '@/stores/auth-store'

const RBAC_MATRIX: Record<string, Set<string>> = {
  owner: new Set([
    'instance_settings:read',
    'instance_settings:write',
    'users:read',
    'users:write',
    'users:invite',
    'users:delete',
    'users:enable',
    'projects:read',
    'projects:write',
    'projects:delete',
    'pipelines:read',
    'pipelines:write',
    'pipelines:delete',
    'builds:read',
    'builds:write',
    'builds:cancel',
    'artifacts:read',
    'artifacts:write',
    'artifacts:delete',
    'runners:read',
    'runners:write',
    'runners:delete',
    'integrations:read',
    'integrations:write',
    'integrations:delete',
  ]),
  admin: new Set([
    'instance_settings:read',
    'instance_settings:write',
    'users:read',
    'users:write',
    'users:invite',
    'users:delete',
    'users:enable',
    'projects:read',
    'projects:write',
    'projects:delete',
    'pipelines:read',
    'pipelines:write',
    'pipelines:delete',
    'builds:read',
    'builds:write',
    'builds:cancel',
    'artifacts:read',
    'artifacts:write',
    'artifacts:delete',
    'runners:read',
    'runners:write',
    'runners:delete',
    'integrations:read',
    'integrations:write',
    'integrations:delete',
  ]),
  developer: new Set([
    'projects:read',
    'projects:write',
    'pipelines:read',
    'pipelines:write',
    'builds:read',
    'builds:write',
    'builds:cancel',
    'artifacts:read',
    'artifacts:write',
    'runners:read',
    'integrations:read',
  ]),
  qa_viewer: new Set([
    'projects:read',
    'pipelines:read',
    'builds:read',
    'artifacts:read',
    'integrations:read',
  ]),
}

export function useHasPermission(resource: string, action: string): boolean {
  const role = useAuthStore((state) => state.user?.role)
  const key = `${resource}:${action}`
  const currentRole = role()
  if (!currentRole) return false
  return RBAC_MATRIX[currentRole]?.has(key) === true
}
