import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { useVerifyBootstrapToken, useSetupStatus } from '@/hooks/use-setup'
import { useSetupStore } from '@/stores/setup-store'
import { ApiClientError } from '@/lib/api'

const bootstrapTokenSchema = z.object({
  token: z.string().min(1, 'Bootstrap token is required'),
})

type BootstrapTokenForm = z.infer<typeof bootstrapTokenSchema>

export const Route = createFileRoute('/setup/')({
  component: BootstrapTokenStep,
  errorComponent: BootstrapTokenError,
})

function BootstrapTokenError({ error }: { error: Error }) {
  return (
    <div className="space-y-4">
      <Alert variant="destructive">
        <AlertTitle>Something went wrong</AlertTitle>
        <AlertDescription>{error.message}</AlertDescription>
      </Alert>
    </div>
  )
}

/** Map backend state to the wizard step index. */
function stateToStep(state: string): number {
  switch (state) {
    case 'bootstrap_pending':
    case 'uninitialized':
      return 0
    case 'idp_configured':
      return 2
    case 'owner_created':
      return 3
    default:
      return 0
  }
}

function BootstrapTokenStep() {
  const navigate = useNavigate()
  const sessionToken = useSetupStore((s) => s.sessionToken)
  const setSessionToken = useSetupStore((s) => s.setSessionToken)
  const setSessionExpiresAt = useSetupStore((s) => s.setSessionExpiresAt)
  const setCurrentStep = useSetupStore((s) => s.setCurrentStep)
  const verifyMutation = useVerifyBootstrapToken()
  const { data: status } = useSetupStatus()

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<BootstrapTokenForm>({
    resolver: zodResolver(bootstrapTokenSchema),
    defaultValues: { token: '' },
  })

  // If backend is already past bootstrap and we have a session, skip ahead
  useEffect(() => {
    if (!status || !sessionToken) return

    const backendStep = stateToStep(status.state)
    if (backendStep >= 1) {
      setCurrentStep(backendStep)
      if (status.state === 'idp_configured') {
        void navigate({ to: '/setup/owner' })
      } else if (status.state === 'owner_created') {
        void navigate({ to: '/setup/complete' })
      }
    }
  }, [status, sessionToken, navigate, setCurrentStep])

  useEffect(() => {
    setCurrentStep(0)
  }, [setCurrentStep])

  const errorMessage = verifyMutation.error
    ? verifyMutation.error instanceof ApiClientError
      ? verifyMutation.error.code === 'token_expired'
        ? 'Bootstrap token has expired. Generate a new one with the CLI.'
        : verifyMutation.error.code === 'token_consumed'
          ? 'Bootstrap token has already been used. Generate a new one with the CLI.'
          : verifyMutation.error.code === 'invalid_token'
            ? 'Invalid bootstrap token. Check the value and try again.'
            : verifyMutation.error.message
      : 'An unexpected error occurred. Please try again.'
    : null

  function onSubmit(data: BootstrapTokenForm) {
    verifyMutation.mutate(data.token.trim(), {
      onSuccess: (res) => {
        setSessionToken(res.session_token)
        setSessionExpiresAt(res.expires_at)
        setCurrentStep(1)
        void navigate({ to: '/setup/oidc' })
      },
    })
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div className="space-y-1">
        <h2 className="text-lg font-medium">Bootstrap Token</h2>
        <p className="text-sm text-muted-foreground">
          Enter the bootstrap token generated by the{' '}
          <code className="bg-muted px-1 py-0.5 text-xs">oore setup open</code>{' '}
          CLI command.
        </p>
      </div>

      <div className="space-y-2">
        <Label htmlFor="bootstrap-token">Token</Label>
        <Input
          id="bootstrap-token"
          type="password"
          placeholder="Paste your bootstrap token"
          {...register('token')}
          disabled={verifyMutation.isPending}
          autoFocus
        />
        {errors.token ? (
          <p className="text-sm text-destructive">{errors.token.message}</p>
        ) : null}
      </div>

      {errorMessage ? (
        <Alert variant="destructive">
          <AlertTitle>Verification failed</AlertTitle>
          <AlertDescription>{errorMessage}</AlertDescription>
        </Alert>
      ) : null}

      <Button
        type="submit"
        disabled={verifyMutation.isPending}
        className="w-full"
      >
        {verifyMutation.isPending ? 'Verifying...' : 'Verify Token'}
      </Button>
    </form>
  )
}
